### ISSUE TITLE
Cisco Shipped Closed

### ISSUE THREAD

**Issue by renet123** [robertcsapo/cisco-meraki-cmx-api-app#1]
It looks like Cisco Shipped has closed.  Anyone know of a alternative?

**Comment by robertcsapo** [comment]
It would be possible to host it on any PaaS, that supports SQLite.

**Comment by robertcsapo** [comment]
@renet123 it would be possible to host it on [https://www.openshift.com/](https://www.openshift.com/), would that work?

**Comment by robertcsapo** [comment]
Added Red Hat OpenShift support https://www.openshift.com/
How-To => https://github.com/robertcsapo/cisco-meraki-cmx-api-app/tree/openshift/openshift
